In [25]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('final_results/experiments_results.csv')

# Define mappings for shortening dataset names
dataset_mapping = {
    "AtrialFibrillation": "AF",
    "CinCECGTorso": "CET",
    "ECG200": "ECG2",
    "ECGFiveDays": "ECG5",
    "EMOPain": "EMO",
    "Epilepsy": "EPI",
    "EyesOpenShut": "EOS",
    "HandMovementDirection": "HMD",
    "Heartbeat": "HRT",
    "MedicalImages": "MI",
    "NerveDamage": "ND",
    "TwoLeadECG": "TECG",
}

# Group by dataset to get unique datasets
grouped = df.groupby('dataset').first().reset_index()

# Initialize a list to store table rows
table_rows = []

# Iterate over each dataset
for _, row in grouped.iterrows():
    dataset_name = row['dataset']
    # Add the shortened name in parentheses
    shortened_name = dataset_mapping.get(dataset_name, dataset_name)  # Use original name if no mapping exists
    dataset_name_formatted = f"{dataset_name} ({shortened_name})"
    
    n_variates = int(row['n_variates'])  # Number of variates (e.g., 1 for univariate)
    ts_length = int(row['ts_length'])    # Time series length
    n_classes = int(row['n_classes'])    # Number of classes
    
    # Calculate train and test sizes (80/20 split)
    total_samples = int(row['df_size'])
    train_size = int(total_samples * 0.8)
    test_size = total_samples - train_size
    
    # Format train and test shapes
    train_shape = f"({train_size}, {n_variates}, {ts_length})"
    test_shape = f"({test_size}, {n_variates}, {ts_length})"
    
    # Append to table rows
    table_rows.append([dataset_name_formatted, train_shape, test_shape, n_classes])

# Generate the LaTeX table
latex_table = """
\\begin{tabular}{l c c c}
\\toprule
\\textbf{Dataset} & \\textbf{Train Shape} & \\textbf{Test Shape} & \\textbf{\\# Classes} \\\\
\\midrule
"""

# Add rows to the table
for row in table_rows:
    latex_table += f"{row[0]} & {row[1]} & {row[2]} & {row[3]} \\\\\n"

# Close the table
latex_table += """\\bottomrule
\\end{tabular}
"""

# Print the LaTeX table
print(latex_table)

# Optionally, save the table to a .tex file
with open('dataset_table.tex', 'w') as f:
    f.write(latex_table)


\begin{tabular}{l c c c}
\toprule
\textbf{Dataset} & \textbf{Train Shape} & \textbf{Test Shape} & \textbf{\# Classes} \\
\midrule
AtrialFibrillation (AF) & (19, 2, 640) & (5, 2, 640) & 3 \\
CinCECGTorso (CET) & (908, 1, 1639) & (228, 1, 1639) & 4 \\
ECG200 (ECG2) & (128, 1, 96) & (32, 1, 96) & 2 \\
ECGFiveDays (ECG5) & (565, 1, 136) & (142, 1, 136) & 2 \\
EMOPain (EMO) & (846, 30, 200) & (212, 30, 200) & 3 \\
Epilepsy (EPI) & (176, 3, 206) & (44, 3, 206) & 4 \\
EyesOpenShut (EOS) & (62, 14, 128) & (16, 14, 128) & 2 \\
HandMovementDirection (HMD) & (149, 10, 400) & (38, 10, 400) & 4 \\
Heartbeat (HRT) & (261, 61, 405) & (66, 61, 405) & 2 \\
MedicalImages (MI) & (729, 1, 99) & (183, 1, 99) & 10 \\
NerveDamage (ND) & (130, 1, 1500) & (33, 1, 1500) & 3 \\
TwoLeadECG (TECG) & (743, 1, 82) & (186, 1, 82) & 2 \\
\bottomrule
\end{tabular}



In [15]:
import numpy as np
from aeon.datasets import load_classification
import pickle
import pandas as pd


data = 'AtrialFibrillation'
X, y = load_classification(data)

print(np.unique(y, return_counts=True))
print(X.shape)

for x in X[y=='s']:
    print(x)


print("-"*70)

for x in X[y=='t']:
    print(x)

(array(['n', 's', 't'], dtype='<U1'), array([10, 10, 10], dtype=int64))
(30, 2, 640)
[[-0.02964  0.00988  0.00988 ... -0.13832 -0.15314 -0.1482 ]
 [ 0.      -0.00988 -0.02964 ...  0.08892  0.0988   0.0988 ]]
[[ 0.66445  1.1645   1.0001  ... -0.0411  -0.1918  -0.1233 ]
 [ 0.02684  0.08723 -0.16775 ...  0.01342 -0.00671  0.00671]]
[[ 0.07686  0.06588  0.02196 ... -0.08784 -0.09333 -0.07137]
 [ 0.1309   0.1309   0.0952  ... -0.05355 -0.04165 -0.01785]]
[[-0.2091  -0.2091  -0.204   ... -0.1938  -0.4131  -0.4233 ]
 [ 0.01104 -0.00552  0.      ... -0.02208  0.03312  0.11592]]
[[-0.01482 -0.03458 -0.03458 ...  0.0494   0.13832  0.08398]
 [ 0.01482  0.01482  0.00494 ... -0.03952 -0.02964  0.00988]]
[[-0.15314 -0.10374 -0.0494  ... -0.1482  -0.13338 -0.12844]
 [ 0.00988  0.01482  0.04446 ...  0.15314  0.0988   0.03952]]
[[-0.05391 -0.06589 -0.08386 ...  0.09584  0.11381  0.09584]
 [ 0.27166  0.30056  0.3179  ...  0.15028  0.2023   0.2312 ]]
[[ 0.12844  0.12844  0.16302 ... -0.10868 -0.09386 -0.

In [28]:
import pandas as pd

# Load the dataset
df = pd.read_csv("final_results/experiments_results.csv")  # Replace with your file path

# Define mappings for shortening dataset and class names
dataset_mapping = {
    "AtrialFibrillation": "AF",
    "CinCECGTorso": "CET",
    "ECG200": "ECG2",
    "ECGFiveDays": "ECG5",
    "EMOPain": "EMO",
    "Epilepsy": "EPI",
    "EyesOpenShut": "EOS",
    "HandMovementDirection": "HMD",
    "Heartbeat": "HRT",
    "MedicalImages": "MI",
    "NerveDamage": "ND",
    "TwoLeadECG": "TECG",
}

# Apply the mappings to shorten dataset names
df['dataset'] = df['dataset'].map(dataset_mapping).fillna(df['dataset'])

# Add percentage to class names
df['class'] = df['class'].astype(str) + " (" + (df['class_perc'] * 100).astype(int).astype(str) + "\%)"

# Sort by dataset and class
df = df.sort_values(by=['dataset', 'class'])

# Initialize variables to track the current dataset
current_dataset = None

# Iterate through the dataset in chunks of 3 rows (one for each model)
for i in range(0, len(df), 3):
    # Get the 3 rows for the current class
    lstm_row = df.iloc[i]
    catch22_row = df.iloc[i + 1]
    rocket_row = df.iloc[i + 2]

    # Print dataset header if it changes
    if lstm_row['dataset'] != current_dataset:
        print(f"\\textbf{{{lstm_row['dataset']}}}")
        current_dataset = lstm_row['dataset']

    # Format values, replacing std of 0.0 with '-'
    def format_value(value, std):
        return f"{round(value, 3)} & {round(std, 3) if std != 0.0 else '-'}"

    # Format the row
    formatted_row = (
        f"& {lstm_row['class']} "
        f"& {format_value(lstm_row['mean'], lstm_row['std'])} & {round(lstm_row['model_acc'], 3)} "
        f"& {format_value(catch22_row['mean'], catch22_row['std'])} & {round(catch22_row['model_acc'], 3)} "
        f"& {format_value(rocket_row['mean'], rocket_row['std'])} & {round(rocket_row['model_acc'], 3)} \\\\"
    )

    # Print the formatted row
    print(formatted_row)

# Print a midrule at the end
print("\\midrule")

\textbf{AF}
& n (33\%) & 0.0 & - & 0.0 & 0.0 & - & 0.333 & 0.0 & - & 0.0 \\
& s (29\%) & 0.0 & - & 0.0 & 0.0 & - & 0.333 & 0.0 & - & 0.0 \\
\textbf{CET}
& 1 (24\%) & 0.566 & 0.117 & 0.996 & 0.499 & 0.142 & 0.986 & 0.536 & 0.102 & 1.0 \\
& 2 (25\%) & 0.51 & 0.109 & 0.996 & 0.442 & 0.135 & 0.986 & 0.489 & 0.089 & 1.0 \\
& 3 (25\%) & 0.524 & 0.115 & 0.996 & 0.448 & 0.147 & 0.986 & 0.489 & 0.1 & 1.0 \\
& 4 (24\%) & 0.419 & 0.101 & 0.996 & 0.456 & 0.145 & 0.986 & 0.431 & 0.083 & 1.0 \\
\textbf{ECG2}
& -1 (33\%) & 0.406 & 0.16 & 0.875 & 0.254 & 0.18 & 0.825 & 0.44 & 0.14 & 0.95 \\
& 1 (66\%) & 0.614 & 0.16 & 0.875 & 0.69 & 0.207 & 0.825 & 0.58 & 0.14 & 0.95 \\
\textbf{ECG5}
& 1 (50\%) & 0.442 & 0.135 & 1.0 & 0.644 & 0.127 & 0.989 & 0.531 & 0.061 & 1.0 \\
& 2 (49\%) & 0.578 & 0.135 & 1.0 & 0.346 & 0.104 & 0.989 & 0.489 & 0.061 & 1.0 \\
\textbf{EMO}
& 0 (77\%) & 0.302 & 0.165 & 0.815 & 0.176 & 0.132 & 0.925 & 0.556 & 0.353 & 0.808 \\
& 1 (14\%) & 0.651 & 0.267 & 0.815 & 0.725 & 0.214 & 0.925 &