In [1]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('results/final_results.csv')

# Define mappings for shortening dataset names
dataset_mapping = {
    "AtrialFibrillation": "AF",
    "CinCECGTorso": "CET",
    "Colposcopy": "COL",
    "ECG200": "ECG",
    "ECG5000": "ECG5",
    "EOGHorizontalSignal": "EOGH",
    "EOGVerticalSignal": "EOGV",
    "EMOPain": "EMO",
    "Epilepsy": "EPI",
    "EyesOpenShut": "EOS",
    "HandMovementDirection": "HMD",
    "Heartbeat": "HRT",
    "MedicalImages": "MI",
    "NerveDamage": "ND",
    "ToeSegmentation1": "TOE",
    "TwoLeadECG": "TECG"
}

# Group by dataset to get unique datasets
grouped = df.groupby('dataset').first().reset_index()

# Initialize a list to store table rows
table_rows = []

# Iterate over each dataset
for _, row in grouped.iterrows():
    dataset_name = row['dataset']
    # Add the shortened name in parentheses
    shortened_name = dataset_mapping.get(dataset_name, dataset_name)  # Use original name if no mapping exists
    dataset_name_formatted = f"{dataset_name} ({shortened_name})"
    
    n_variates = int(row['n_variates'])  # Number of variates (e.g., 1 for univariate)
    ts_length = int(row['ts_length'])    # Time series length
    n_classes = int(row['n_classes'])    # Number of classes
    
    # Calculate train and test sizes (80/20 split)
    total_samples = int(row['df_size'])
    train_size = int(total_samples * 0.8)
    test_size = total_samples - train_size
    
    # Format train and test shapes
    train_shape = f"({train_size}, {n_variates}, {ts_length})"
    test_shape = f"({test_size}, {n_variates}, {ts_length})"
    
    # Append to table rows
    table_rows.append([dataset_name_formatted, train_shape, test_shape, n_classes])

# Generate the LaTeX table
latex_table = """
\\begin{tabular}{l c c c}
\\toprule
\\textbf{Dataset} & \\textbf{Train Shape} & \\textbf{Test Shape} & \\textbf{\\# Classes} \\\\
\\midrule
"""

# Add rows to the table
for row in table_rows:
    latex_table += f"{row[0]} & {row[1]} & {row[2]} & {row[3]} \\\\\n"

# Close the table
latex_table += """\\bottomrule
\\end{tabular}
"""

# Print the LaTeX table
print(latex_table)

# Optionally, save the table to a .tex file
with open('dataset_table.tex', 'w') as f:
    f.write(latex_table)


\begin{tabular}{l c c c}
\toprule
\textbf{Dataset} & \textbf{Train Shape} & \textbf{Test Shape} & \textbf{\# Classes} \\
\midrule
AtrialFibrillation (AF) & (19, 2, 640) & (5, 2, 640) & 3 \\
CinCECGTorso (CET) & (908, 1, 1639) & (228, 1, 1639) & 4 \\
Colposcopy (COL) & (128, 1, 180) & (32, 1, 180) & 6 \\
ECG200 (ECG) & (128, 1, 96) & (32, 1, 96) & 2 \\
ECG5000 (ECG5) & (3200, 1, 140) & (800, 1, 140) & 5 \\
EMOPain (EMO) & (846, 30, 200) & (212, 30, 200) & 3 \\
EOGHorizontalSignal (EOGH) & (463, 1, 1250) & (116, 1, 1250) & 12 \\
EOGVerticalSignal (EOGV) & (463, 1, 1250) & (116, 1, 1250) & 12 \\
Epilepsy (EPI) & (176, 3, 206) & (44, 3, 206) & 4 \\
EyesOpenShut (EOS) & (62, 14, 128) & (16, 14, 128) & 2 \\
HandMovementDirection (HMD) & (149, 10, 400) & (38, 10, 400) & 4 \\
Heartbeat (HRT) & (261, 61, 405) & (66, 61, 405) & 2 \\
MedicalImages (MI) & (729, 1, 99) & (183, 1, 99) & 10 \\
NerveDamage (ND) & (130, 1, 1500) & (33, 1, 1500) & 3 \\
ToeSegmentation1 (TOE) & (171, 1, 277) & (43, 1, 2

In [15]:
import numpy as np
from aeon.datasets import load_classification
import pickle
import pandas as pd


data = 'AtrialFibrillation'
X, y = load_classification(data)

print(np.unique(y, return_counts=True))
print(X.shape)

for x in X[y=='s']:
    print(x)


print("-"*70)

for x in X[y=='t']:
    print(x)

(array(['n', 's', 't'], dtype='<U1'), array([10, 10, 10], dtype=int64))
(30, 2, 640)
[[-0.02964  0.00988  0.00988 ... -0.13832 -0.15314 -0.1482 ]
 [ 0.      -0.00988 -0.02964 ...  0.08892  0.0988   0.0988 ]]
[[ 0.66445  1.1645   1.0001  ... -0.0411  -0.1918  -0.1233 ]
 [ 0.02684  0.08723 -0.16775 ...  0.01342 -0.00671  0.00671]]
[[ 0.07686  0.06588  0.02196 ... -0.08784 -0.09333 -0.07137]
 [ 0.1309   0.1309   0.0952  ... -0.05355 -0.04165 -0.01785]]
[[-0.2091  -0.2091  -0.204   ... -0.1938  -0.4131  -0.4233 ]
 [ 0.01104 -0.00552  0.      ... -0.02208  0.03312  0.11592]]
[[-0.01482 -0.03458 -0.03458 ...  0.0494   0.13832  0.08398]
 [ 0.01482  0.01482  0.00494 ... -0.03952 -0.02964  0.00988]]
[[-0.15314 -0.10374 -0.0494  ... -0.1482  -0.13338 -0.12844]
 [ 0.00988  0.01482  0.04446 ...  0.15314  0.0988   0.03952]]
[[-0.05391 -0.06589 -0.08386 ...  0.09584  0.11381  0.09584]
 [ 0.27166  0.30056  0.3179  ...  0.15028  0.2023   0.2312 ]]
[[ 0.12844  0.12844  0.16302 ... -0.10868 -0.09386 -0.

In [3]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('results/final_results.csv')

# Define mappings for shortening dataset names
dataset_mapping = {
    "AtrialFibrillation": "AF",
    "CinCECGTorso": "CET",
    "Colposcopy": "COL",
    "ECG200": "ECG",
    "ECG5000": "ECG5",
    "EOGHorizontalSignal": "EOGH",
    "EOGVerticalSignal": "EOGV",
    "EMOPain": "EMO",
    "Epilepsy": "EPI",
    "EyesOpenShut": "EOS",
    "HandMovementDirection": "HMD",
    "Heartbeat": "HRT",
    "MedicalImages": "MI",
    "NerveDamage": "ND",
    "ToeSegmentation1": "TOE",
    "TwoLeadECG": "TECG"
}

# Apply the mappings to shorten dataset names
df['dataset'] = df['dataset'].map(dataset_mapping).fillna(df['dataset'])

# Add percentage to class names
df['class'] = df['class'].astype(str) + " (" + (df['class_perc'] * 100).astype(int).astype(str) + "\%)"

# Sort by dataset and class
df = df.sort_values(by=['dataset', 'class'])

# Initialize variables to track the current dataset
current_dataset = None

# Iterate through the dataset in chunks of 3 rows (one for each model)
for i in range(0, len(df), 3):
    # Get the 3 rows for the current class
    lstm_row = df.iloc[i]
    catch22_row = df.iloc[i + 1]
    rocket_row = df.iloc[i + 2]

    # Print dataset header if it changes
    if lstm_row['dataset'] != current_dataset:
        print(f"\\textbf{{{lstm_row['dataset']}}}")
        current_dataset = lstm_row['dataset']

    # Format values, replacing std of 0.0 with '-'
    def format_value(value, std):
        return f"{round(value, 3)} & {round(std, 3) if std != 0.0 else '-'}"

    # Format the row
    formatted_row = (
        f"& {lstm_row['class']} "
        f"& {format_value(lstm_row['mean'], lstm_row['std'])} & {round(lstm_row['model_acc'], 3)} "
        f"& {format_value(catch22_row['mean'], catch22_row['std'])} & {round(catch22_row['model_acc'], 3)} "
        f"& {format_value(rocket_row['mean'], rocket_row['std'])} & {round(rocket_row['model_acc'], 3)} \\\\"
    )

    # Print the formatted row
    print(formatted_row)

# Print a midrule at the end
print("\\midrule")

\textbf{AF}
& n (33\%) & 0.0 & - & 0.0 & 0.0 & - & 0.333 & 0.0 & - & 0.0 \\
& s (29\%) & 0.0 & - & 0.0 & 0.0 & - & 0.333 & 0.0 & - & 0.0 \\
& t (37\%) & 0.0 & - & 0.0 & 0.0 & - & 0.333 & 0.0 & - & 0.0 \\
\textbf{CET}
& 1 (24\%) & 0.575 & 0.134 & 0.996 & 0.571 & 0.15 & 0.979 & 0.563 & 0.061 & 1.0 \\
& 2 (25\%) & 0.474 & 0.136 & 0.996 & 0.424 & 0.137 & 0.979 & 0.483 & 0.067 & 1.0 \\
& 3 (25\%) & 0.524 & 0.085 & 0.996 & 0.489 & 0.14 & 0.979 & 0.518 & 0.065 & 1.0 \\
& 4 (24\%) & 0.447 & 0.104 & 0.996 & 0.417 & 0.177 & 0.979 & 0.469 & 0.094 & 1.0 \\
\textbf{COL}
& 0 (8\%) & 0.0 & - & 0.45 & 0.0 & - & 0.425 & 0.0 & - & 0.3 \\
& 1 (11\%) & 0.0 & - & 0.45 & 0.0 & - & 0.425 & 0.0 & - & 0.3 \\
& 2 (10\%) & 0.0 & - & 0.45 & 0.274 & 0.348 & 0.425 & 0.0 & - & 0.3 \\
& 3 (25\%) & 0.0 & - & 0.45 & 0.0 & - & 0.425 & 0.0 & - & 0.3 \\
& 4 (15\%) & 0.0 & - & 0.45 & 0.785 & 0.055 & 0.425 & 0.32 & - & 0.3 \\
& 5 (28\%) & 0.43 & 0.164 & 0.45 & 0.078 & 0.066 & 0.425 & 0.67 & 0.172 & 0.3 \\
\textbf{ECG}
& -1 

In [2]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('results/final_results.csv')

# Define mappings for shortening dataset names
dataset_mapping = {
    "AtrialFibrillation": "AF",
    "CinCECGTorso": "CET",
    "Colposcopy": "COL",
    "ECG200": "ECG",
    "ECG5000": "ECG5",
    "EOGHorizontalSignal": "EOGH",
    "EOGVerticalSignal": "EOGV",
    "EMOPain": "EMO",
    "Epilepsy": "EPI",
    "EyesOpenShut": "EOS",
    "HandMovementDirection": "HMD",
    "Heartbeat": "HRT",
    "MedicalImages": "MI",
    "NerveDamage": "ND",
    "ToeSegmentation1": "TOE",
    "TwoLeadECG": "TECG"
}

# Apply the mappings to shorten dataset names
df['dataset'] = df['dataset'].map(dataset_mapping).fillna(df['dataset'])

# Add percentage to class names
df['class'] = df['class'].astype(str) + " (" + (df['class_perc'] * 100).astype(int).astype(str) + "\%)"

# Sort by dataset and class
df = df.sort_values(by=['dataset', 'class'])

data_results = []

# Now compute and print averages for each dataset and model
unique_datasets = df['dataset'].unique()

for dataset in unique_datasets:
    dataset_df = df[df['dataset'] == dataset]
    
    # Calculate averages for each model
    lstm_avg_mean = dataset_df[dataset_df['model'] == 'lstm']['mean'].mean()
    lstm_avg_std = dataset_df[dataset_df['model'] == 'lstm']['std'].mean()
    lstm_avg_acc = dataset_df[dataset_df['model'] == 'lstm']['model_acc'].mean()
    
    catch22_avg_mean = dataset_df[dataset_df['model'] == 'catch22']['mean'].mean()
    catch22_avg_std = dataset_df[dataset_df['model'] == 'catch22']['std'].mean()
    catch22_avg_acc = dataset_df[dataset_df['model'] == 'catch22']['model_acc'].mean()
    
    rocket_avg_mean = dataset_df[dataset_df['model'] == 'rocket']['mean'].mean()
    rocket_avg_std = dataset_df[dataset_df['model'] == 'rocket']['std'].mean()
    rocket_avg_acc = dataset_df[dataset_df['model'] == 'rocket']['model_acc'].mean()
    
    # Format the averages row
    def format_avg_value(value, std):
        return f"{round(value, 3)} & {round(std, 3) if std != 0.0 else '-'}"

    formatted_avg_row = (
        f"\\textbf{{{dataset}}} "
        f"& {format_avg_value(lstm_avg_mean, lstm_avg_std)} & {round(lstm_avg_acc, 3)} "
        f"& {format_avg_value(catch22_avg_mean, catch22_avg_std)} & {round(catch22_avg_acc, 3)} "
        f"& {format_avg_value(rocket_avg_mean, rocket_avg_std)} & {round(rocket_avg_acc, 3)} \\\\"
    )
    
    row = [lstm_avg_mean, lstm_avg_std, lstm_avg_acc,
           catch22_avg_mean, catch22_avg_std, catch22_avg_acc,
           rocket_avg_mean, rocket_avg_std, rocket_avg_acc]
    
    data_results.append(row)
    print(formatted_avg_row)


columns = ['LSTM Mean', 'LSTM Std', 'LSTM Acc',
           'Catch22 Mean', 'Catch22 Std', 'Catch22 Acc',
           'ROCKET Mean', 'ROCKET Std', 'ROCKET Acc']

df_results = pd.DataFrame(data_results, columns=columns)
df_results.to_csv('results/average_results.csv', index=False)


\textbf{AF} & 0.0 & - & 0.0 & 0.0 & - & 0.333 & 0.0 & - & 0.0 \\
\textbf{CET} & 0.505 & 0.115 & 0.996 & 0.475 & 0.151 & 0.979 & 0.508 & 0.072 & 1.0 \\
\textbf{COL} & 0.072 & 0.027 & 0.45 & 0.19 & 0.078 & 0.425 & 0.165 & 0.029 & 0.3 \\
\textbf{ECG} & 0.52 & 0.081 & 0.85 & 0.475 & 0.145 & 0.8 & 0.52 & 0.125 & 0.95 \\
\textbf{ECG5} & 0.415 & 0.128 & 0.956 & 0.311 & 0.118 & 0.948 & 0.42 & 0.14 & 0.963 \\
\textbf{EMO} & 0.501 & 0.026 & 0.777 & 0.563 & 0.163 & 0.906 & 0.3 & 0.231 & 0.789 \\
\textbf{EOGH} & 0.15 & 0.089 & 0.262 & 0.352 & 0.224 & 0.786 & 0.446 & 0.199 & 0.89 \\
\textbf{EOGV} & 0.087 & 0.069 & 0.207 & 0.338 & 0.234 & 0.662 & 0.455 & 0.178 & 0.828 \\
\textbf{EOS} & 0.0 & - & 0.55 & 0.47 & 0.174 & 0.65 & 0.52 & 0.106 & 0.5 \\
\textbf{EPI} & 0.497 & 0.182 & 0.764 & 0.44 & 0.168 & 0.982 & 0.461 & 0.159 & 0.982 \\
\textbf{HMD} & 0.254 & 0.243 & 0.255 & 0.082 & 0.041 & 0.319 & 0.452 & 0.143 & 0.383 \\
\textbf{HRT} & 0.0 & - & 0.61 & 0.449 & 0.101 & 0.695 & 0.52 & 0.183 & 0.646 \\
\te